version: "3.6"

services:
  database:
    image: postgres:13.7
    container_name: flutter-lp-database
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    ports:
      - "15432:5432"
    env_file:
      - .env.database
    volumes:
      - database_data:/var/lib/postgresql/data
      - database_logs:/var/log
  gqlengine:
    image: hasura/graphql-engine:v2.10.1
    container_name: flutter-lp-gqlengine
    ports:
      - "18080:8080"
    depends_on:
      - "database"
    env_file:
      - .env.gqlengine

volumes:
    database_data:
    database_logs:
